// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/public/dapp/banner/list": {
            "post": {
                "description": "获取轮播图列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页"
                ],
                "summary": "获取轮播图列表",
                "operationId": "GetBannerList",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.GetBannerListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.GetBannerListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/manage/banner/list": {
            "post": {
                "description": "获取轮播图列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dapp管理"
                ],
                "summary": "获取轮播图列表",
                "operationId": "GetManageBannerList",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.GetManageBannerListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.GetManageBannerListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/manage/banner/operation": {
            "post": {
                "description": "轮播图操作管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dapp管理"
                ],
                "summary": "轮播图操作管理",
                "operationId": "ManageBannerOperation",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.ManageBannerOperationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.ManageBannerOperationResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/manage/discover/tool/categories/list": {
            "post": {
                "description": "工具分类列表管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页管理"
                ],
                "summary": "工具分类列表管理",
                "operationId": "GetManageDiscoverToolCategoriesList",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.GetManageDiscoverToolCategoriesListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.GetManageDiscoverToolCategoriesListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/manage/discover/tool/categories/operation": {
            "post": {
                "description": "工具分类操作管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页管理"
                ],
                "summary": "工具分类操作管理",
                "operationId": "ManageDiscoverToolCategoriesOperation",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.ManageDiscoverToolCategoriesOperationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.ManageDiscoverToolCategoriesOperationResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/manage/discover/tool/info/list": {
            "post": {
                "description": "工具列表管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页管理"
                ],
                "summary": "工具列表管理",
                "operationId": "GetManageDiscoverToolInfoList",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.GetManageDiscoverToolInfoListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.GetManageDiscoverToolInfoListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/manage/discover/tool/info/operation": {
            "post": {
                "description": "工具操作管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页管理"
                ],
                "summary": "工具操作管理",
                "operationId": "ManageDiscoverToolInfoOperation",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.ManageDiscoverToolInfoOperationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.ManageDiscoverToolInfoOperationResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/manage/discover/toolbar/list": {
            "post": {
                "description": "发现页工具栏列表管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页管理"
                ],
                "summary": "发现页工具栏列表管理",
                "operationId": "GetManageDiscovertoolbarList",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.GetManageDiscovertoolbarListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.GetManageDiscovertoolbarListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/manage/discover/toolbar/operation": {
            "post": {
                "description": "发现页工具栏操作管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页管理"
                ],
                "summary": "发现页工具栏操作管理",
                "operationId": "ManageDiscovertoolbarOperation",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.ManageDiscovertoolbarOperationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.ManageDiscovertoolbarOperationResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/manage/network/list": {
            "post": {
                "description": "区块网络列表管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dapp管理"
                ],
                "summary": "区块网络列表管理",
                "operationId": "GetManageNetworkList",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.GetManageNetworkListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.GetManageNetworkListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/manage/network/operation": {
            "post": {
                "description": "区块网络操作管理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dapp管理"
                ],
                "summary": "区块网络操作管理",
                "operationId": "ManageNetworkOperation",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.ManageNetworkOperationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.ManageNetworkOperationResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/network/list": {
            "post": {
                "description": "获取网络列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页"
                ],
                "summary": "获取网络列表",
                "operationId": "GetNetworkList",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.GetNetworkListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.GetNetworkListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/tool/categories/list": {
            "post": {
                "description": "获取工具分类列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页"
                ],
                "summary": "获取工具分类列表",
                "operationId": "GetDiscoverToolCategoriesList",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.GetDiscoverToolCategoriesListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.GetDiscoverToolCategoriesListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/tool/event/list": {
            "post": {
                "description": "发现页工具访问记录列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页"
                ],
                "summary": "发现页工具访问记录列表",
                "operationId": "GetDiscoverToolEventList",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.GetDiscoverToolEventListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.GetDiscoverToolEventListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/tool/event/operation": {
            "post": {
                "description": "发现页工具访问记录操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页"
                ],
                "summary": "发现页工具访问记录操作",
                "operationId": "DiscoverToolEventOperation",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.DiscoverToolEventOperationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.DiscoverToolEventOperationResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/tool/favorites/list": {
            "post": {
                "description": "获取发现页工具收藏列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页"
                ],
                "summary": "获取发现页工具收藏列表",
                "operationId": "GetDiscoverToolFavoritesList",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.GetDiscoverToolFavoritesListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.GetDiscoverToolFavoritesListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/tool/favorites/operation": {
            "post": {
                "description": "发现页工具收藏操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页"
                ],
                "summary": "发现页工具收藏操作",
                "operationId": "DiscoverToolFavoritesOperation",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.DiscoverToolFavoritesOperationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.DiscoverToolFavoritesOperationResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/tool/info/list": {
            "post": {
                "description": "获取工具列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页"
                ],
                "summary": "获取工具列表",
                "operationId": "GetDiscoverToolInfoList",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.GetDiscoverToolInfoListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.GetDiscoverToolInfoListResp"
                        }
                    }
                }
            }
        },
        "/api/v1/public/dapp/toolbar/list": {
            "post": {
                "description": "获取发现页工具栏列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "发现页"
                ],
                "summary": "获取发现页工具栏列表",
                "operationId": "GetDiscoverToolbarList",
                "parameters": [
                    {
                        "description": "请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/protos.GetDiscoverToolbarListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/protos.GetDiscoverToolbarListResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "protos.CategoryInfoItem": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "分类ID",
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "title": {
                    "description": "分类标题",
                    "type": "string"
                }
            }
        },
        "protos.DiscoverToolEventOperationReq": {
            "type": "object",
            "properties": {
                "event_type": {
                    "description": "view/click/share/fav/comment",
                    "type": "string"
                },
                "tool_id": {
                    "type": "integer"
                }
            }
        },
        "protos.DiscoverToolEventOperationResp": {
            "type": "object"
        },
        "protos.DiscoverToolFavoritesOperationReq": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "1-显示 2-隐藏",
                    "type": "integer"
                },
                "tool_id": {
                    "type": "integer"
                }
            }
        },
        "protos.DiscoverToolFavoritesOperationResp": {
            "type": "object"
        },
        "protos.EventCategoryInfoItem": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "分类ID",
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "title": {
                    "description": "分类标题",
                    "type": "string"
                }
            }
        },
        "protos.EventNetWorkInfoItem": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "string"
                },
                "explorer_url": {
                    "description": "浏览器地址，例如 https://bscscan.com",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "description": "图标",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rpc_url": {
                    "description": "默认 RPC，非必填",
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "protos.FavoritesCategoryInfoItem": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "分类ID",
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "title": {
                    "description": "分类标题",
                    "type": "string"
                }
            }
        },
        "protos.FavoritesNetWorkInfoItem": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "string"
                },
                "explorer_url": {
                    "description": "浏览器地址，例如 https://bscscan.com",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "description": "图标",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rpc_url": {
                    "description": "默认 RPC，非必填",
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "protos.GetBannerListReq": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "protos.GetBannerListResp": {
            "type": "object",
            "properties": {
                "created_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "expiration_time": {
                    "description": "过期时间",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "need_login": {
                    "description": "是否需要登录：1-不需要，2-需要",
                    "type": "integer"
                },
                "position": {
                    "description": "位置 key",
                    "type": "string"
                },
                "skip_target": {
                    "description": "跳转目标：1-H5,2-客服",
                    "type": "integer"
                },
                "skip_url": {
                    "description": "跳转URL",
                    "type": "string"
                },
                "sort": {
                    "description": "顺序",
                    "type": "integer"
                },
                "start_at": {
                    "description": "开始时间",
                    "type": "string"
                },
                "status": {
                    "description": "状态：1-上架，2-下架",
                    "type": "integer"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "updated_time": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "protos.GetDiscoverToolCategoriesListReq": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "protos.GetDiscoverToolCategoriesListResp": {
            "type": "object",
            "properties": {
                "created_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "说明",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "is_show": {
                    "description": "1-显示，2-隐藏",
                    "type": "integer"
                },
                "skip_url": {
                    "description": "跳转URL",
                    "type": "string"
                },
                "sort": {
                    "description": "顺序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态：1-上架，2-下架",
                    "type": "integer"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "updated_time": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "protos.GetDiscoverToolEventListReq": {
            "type": "object",
            "properties": {
                "event_type": {
                    "description": "view/click/share/fav/comment",
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "protos.GetDiscoverToolEventListResp": {
            "type": "object",
            "properties": {
                "category_info_ids": {
                    "description": "关联分类ID列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protos.EventCategoryInfoItem"
                    }
                },
                "community_tutorial": {
                    "description": "社区教程跳转URL",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "service_support": {
                    "description": "服务支持内容",
                    "type": "string"
                },
                "short_desc": {
                    "description": "简短描述",
                    "type": "string"
                },
                "skip_url": {
                    "description": "跳转URL",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "status": {
                    "description": "1-显示 2-隐藏",
                    "type": "integer"
                },
                "support_network_info_ids": {
                    "description": "支持的网络ID列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protos.EventNetWorkInfoItem"
                    }
                },
                "thumbnail": {
                    "description": "缩略图 URL",
                    "type": "string"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "token": {
                    "description": "token跳转URL",
                    "type": "string"
                },
                "tool_id": {
                    "type": "integer"
                }
            }
        },
        "protos.GetDiscoverToolFavoritesListReq": {
            "type": "object",
            "properties": {
                "net_work_id": {
                    "description": "网络ID",
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "protos.GetDiscoverToolFavoritesListResp": {
            "type": "object",
            "properties": {
                "category_info_ids": {
                    "description": "关联分类ID列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protos.FavoritesCategoryInfoItem"
                    }
                },
                "community_tutorial": {
                    "description": "社区教程跳转URL",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "service_support": {
                    "description": "服务支持内容",
                    "type": "string"
                },
                "short_desc": {
                    "description": "简短描述",
                    "type": "string"
                },
                "skip_url": {
                    "description": "跳转URL",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "status": {
                    "description": "1-显示 2-隐藏",
                    "type": "integer"
                },
                "support_network_info_ids": {
                    "description": "支持的网络ID列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protos.FavoritesNetWorkInfoItem"
                    }
                },
                "thumbnail": {
                    "description": "缩略图 URL",
                    "type": "string"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "token": {
                    "description": "token跳转URL",
                    "type": "string"
                },
                "tool_id": {
                    "type": "integer"
                }
            }
        },
        "protos.GetDiscoverToolInfoListReq": {
            "type": "object",
            "properties": {
                "categories_id": {
                    "description": "分类ID",
                    "type": "integer"
                },
                "net_work_id": {
                    "description": "网络ID",
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "tag": {
                    "description": "标签",
                    "type": "string"
                },
                "tool_name": {
                    "description": "工具名称",
                    "type": "string"
                }
            }
        },
        "protos.GetDiscoverToolInfoListResp": {
            "type": "object",
            "properties": {
                "category_info_ids": {
                    "description": "关联分类ID列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protos.CategoryInfoItem"
                    }
                },
                "community_tutorial": {
                    "description": "社区教程跳转URL",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "service_support": {
                    "description": "服务支持内容",
                    "type": "string"
                },
                "short_desc": {
                    "description": "简短描述",
                    "type": "string"
                },
                "skip_url": {
                    "description": "跳转URL",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "status": {
                    "description": "1-显示 2-隐藏",
                    "type": "integer"
                },
                "support_network_info_ids": {
                    "description": "支持的网络ID列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protos.NetWorkInfoItem"
                    }
                },
                "thumbnail": {
                    "description": "缩略图 URL",
                    "type": "string"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "token": {
                    "description": "token跳转URL",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "protos.GetDiscoverToolbarListReq": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "protos.GetDiscoverToolbarListResp": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "tag": {
                    "description": "标签",
                    "type": "string"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                }
            }
        },
        "protos.GetManageBannerListReq": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "protos.GetManageBannerListResp": {
            "type": "object",
            "properties": {
                "created_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "expiration_time": {
                    "description": "过期时间",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "need_login": {
                    "description": "是否需要登录：1-不需要，2-需要",
                    "type": "integer"
                },
                "position": {
                    "description": "位置 key",
                    "type": "string"
                },
                "skip_target": {
                    "description": "跳转目标：1-H5,2-客服",
                    "type": "integer"
                },
                "skip_url": {
                    "description": "跳转URL",
                    "type": "string"
                },
                "sort": {
                    "description": "顺序",
                    "type": "integer"
                },
                "start_at": {
                    "description": "开始时间",
                    "type": "string"
                },
                "status": {
                    "description": "状态：1-上架，2-下架",
                    "type": "integer"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "updated_time": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "protos.GetManageDiscoverToolCategoriesListReq": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "protos.GetManageDiscoverToolCategoriesListResp": {
            "type": "object",
            "properties": {
                "created_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "description": {
                    "description": "说明",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "is_show": {
                    "description": "1-显示，2-隐藏",
                    "type": "integer"
                },
                "skip_url": {
                    "description": "跳转URL",
                    "type": "string"
                },
                "sort": {
                    "description": "顺序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态：1-上架，2-下架",
                    "type": "integer"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "updated_time": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "protos.GetManageDiscoverToolInfoListReq": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "protos.GetManageDiscoverToolInfoListResp": {
            "type": "object",
            "properties": {
                "category_info_ids": {
                    "description": "关联分类ID列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protos.ManageCategoryInfoItem"
                    }
                },
                "community_tutorial": {
                    "description": "社区教程跳转URL",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "service_support": {
                    "description": "服务支持内容",
                    "type": "string"
                },
                "short_desc": {
                    "description": "简短描述",
                    "type": "string"
                },
                "skip_url": {
                    "description": "跳转URL",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "status": {
                    "description": "1-显示 2-隐藏",
                    "type": "integer"
                },
                "support_network_info_ids": {
                    "description": "支持的网络ID列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/protos.ManageNetWorkInfoItem"
                    }
                },
                "tags": {
                    "description": "标签",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "thumbnail": {
                    "description": "缩略图 URL",
                    "type": "string"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "token": {
                    "description": "token跳转URL",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "protos.GetManageDiscovertoolbarListReq": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "protos.GetManageDiscovertoolbarListResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "tag": {
                    "description": "标签: hot-热门 new-最新",
                    "type": "string"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                }
            }
        },
        "protos.GetManageNetworkListReq": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "protos.GetManageNetworkListResp": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "description": "链ID，如 1、56、solana",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "explorer_url": {
                    "description": "浏览器地址，例如 https://bscscan.com",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "description": "图标",
                    "type": "string"
                },
                "name": {
                    "description": "网络名称，如 Ethereum、BSC、Solana",
                    "type": "string"
                },
                "rpc_url": {
                    "description": "默认 RPC，非必填",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态 1启用 2禁用",
                    "type": "integer"
                },
                "symbol": {
                    "description": "链主币符号，例如 ETH、BNB、SOL",
                    "type": "string"
                }
            }
        },
        "protos.GetNetworkListReq": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                }
            }
        },
        "protos.GetNetworkListResp": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "description": "链ID，如 1、56、solana",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "explorer_url": {
                    "description": "浏览器地址，例如 https://bscscan.com",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "description": "图标",
                    "type": "string"
                },
                "name": {
                    "description": "网络名称，如 Ethereum、BSC、Solana",
                    "type": "string"
                },
                "rpc_url": {
                    "description": "默认 RPC，非必填",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态 1启用 2禁用",
                    "type": "integer"
                },
                "symbol": {
                    "description": "链主币符号，例如 ETH、BNB、SOL",
                    "type": "string"
                }
            }
        },
        "protos.ManageBannerOperationReq": {
            "type": "object",
            "properties": {
                "expiration_time": {
                    "description": "过期时间",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "need_login": {
                    "description": "是否需要登录：1-不需要，2-需要",
                    "type": "integer"
                },
                "operation_type": {
                    "description": "操作类型：1-新增，2-编辑，3-删除",
                    "type": "integer"
                },
                "position": {
                    "description": "位置 key",
                    "type": "string"
                },
                "skip_target": {
                    "description": "跳转目标：1-H5,2-客服",
                    "type": "integer"
                },
                "skip_url": {
                    "description": "跳转URL",
                    "type": "string"
                },
                "sort": {
                    "description": "顺序",
                    "type": "integer"
                },
                "start_at": {
                    "description": "开始时间",
                    "type": "string"
                },
                "status": {
                    "description": "状态：1-上架，2-下架",
                    "type": "integer"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                }
            }
        },
        "protos.ManageBannerOperationResp": {
            "type": "object"
        },
        "protos.ManageCategoryInfoItem": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "分类ID",
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "title": {
                    "description": "分类标题",
                    "type": "string"
                }
            }
        },
        "protos.ManageDiscoverToolCategoriesOperationReq": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "说明",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "is_show": {
                    "description": "1-显示，2-隐藏",
                    "type": "integer"
                },
                "operation_type": {
                    "description": "操作类型：1-新增，2-编辑，3-删除",
                    "type": "integer"
                },
                "skip_url": {
                    "description": "跳转URL",
                    "type": "string"
                },
                "sort": {
                    "description": "顺序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态：1-上架，2-下架",
                    "type": "integer"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                }
            }
        },
        "protos.ManageDiscoverToolCategoriesOperationResp": {
            "type": "object"
        },
        "protos.ManageDiscoverToolInfoOperationReq": {
            "type": "object",
            "properties": {
                "category_ids": {
                    "description": "关联分类ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "community_tutorial": {
                    "description": "社区教程跳转URL",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "img_href": {
                    "description": "图片地址",
                    "type": "string"
                },
                "operation_type": {
                    "description": "操作类型：1-新增，2-编辑，3-删除",
                    "type": "integer"
                },
                "service_support": {
                    "description": "服务支持内容",
                    "type": "string"
                },
                "short_desc": {
                    "description": "简短描述",
                    "type": "string"
                },
                "skip_url": {
                    "description": "跳转URL",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "status": {
                    "description": "1-显示 2-隐藏",
                    "type": "integer"
                },
                "support_network_ids": {
                    "description": "支持的网络ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tags": {
                    "description": "标签: hot-热门 new-最新 top - 置顶",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "thumbnail": {
                    "description": "缩略图 URL",
                    "type": "string"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "token": {
                    "description": "token跳转URL",
                    "type": "string"
                }
            }
        },
        "protos.ManageDiscoverToolInfoOperationResp": {
            "type": "object"
        },
        "protos.ManageDiscovertoolbarOperationReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "img_href": {
                    "type": "string"
                },
                "operation_type": {
                    "description": "操作类型：1-新增，2-编辑，3-删除",
                    "type": "integer"
                },
                "sort": {
                    "type": "integer"
                },
                "tag": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "protos.ManageDiscovertoolbarOperationResp": {
            "type": "object"
        },
        "protos.ManageNetWorkInfoItem": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "string"
                },
                "explorer_url": {
                    "description": "浏览器地址，例如 https://bscscan.com",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "description": "图标",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rpc_url": {
                    "description": "默认 RPC，非必填",
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "protos.ManageNetworkOperationReq": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "description": "链ID，如 1、56、solana",
                    "type": "string"
                },
                "explorer_url": {
                    "description": "浏览器地址，例如 https://bscscan.com",
                    "type": "string"
                },
                "id": {
                    "description": "主键ID",
                    "type": "integer"
                },
                "logo": {
                    "description": "图标",
                    "type": "string"
                },
                "name": {
                    "description": "网络名称，如 Ethereum、BSC、Solana",
                    "type": "string"
                },
                "operation_type": {
                    "description": "操作类型：1-新增，2-编辑，3-删除",
                    "type": "integer"
                },
                "rpc_url": {
                    "description": "默认 RPC，非必填",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "status": {
                    "description": "状态 1启用 2禁用",
                    "type": "integer"
                },
                "symbol": {
                    "description": "链主币符号，例如 ETH、BNB、SOL",
                    "type": "string"
                }
            }
        },
        "protos.ManageNetworkOperationResp": {
            "type": "object"
        },
        "protos.NetWorkInfoItem": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "string"
                },
                "explorer_url": {
                    "description": "浏览器地址，例如 https://bscscan.com",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "description": "图标",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rpc_url": {
                    "description": "默认 RPC，非必填",
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
